### ISSUE TITLE
Accept color as int instead of resource

### ISSUE THREAD

**Issue by bernaferrari** [Karn/notify#15]
Hi, I would like to set the color programatically, like this:

```
.header {
    this.icon = R.drawable.vector_sync
    this.color = 0xff123456.toInt()
}
```

However you only accept the resource. By looking at your code, you are explicitly calling getColor on buildNotification. Could you add a way for using non-resourced color?

**Comment by Karn** [comment]
@bernaferrari yeah, I'll take a look at a possible solution. The easiest is to set via an overloaded setter. I'll investigate!

**Comment by bernaferrari** [comment]
You could also make setColorRes/setColor kind of thing, but solution wouldn't be beautiful

**Comment by Karn** [comment]
@bernaferrari I've put up the PR above. Let me know if the changes are in line with your initial proposition.

**Comment by bernaferrari** [comment]
Looks great for me, exactly this!

**Comment by Karn** [comment]
Great! I've merged the changes and will cut a release later this week. If you'd like to get an early start you can use the develop snapshot (`develop-SNAPSHOT`) instead of a version number in your `build.gradle`.

**Comment by bernaferrari** [comment]
Great, thanks! It will be of great use here:
https://github.com/bernaferrari/ChangeDetection
