### ISSUE TITLE
Calling from Java

### ISSUE THREAD

**Issue by gurupras** [Karn/notify#27]
I'm not too familiar with Kotlin and thus I'm trying to use this library from Java and am having a tough time.

Could you kindly provide a couple of examples of how to go about achieving this? In particular, how can 
 I set up the `Payload.Meta` object and possibly `Actions` in the notification?

**Comment by Karn** [comment]
This is a good question. While it would be a great feature to have backward compatibility, Notify requires language features that are just not supported by Java. As such, there is no planned compatibility for Java in the near future.
