### ISSUE TITLE
minSdkVersion 17 

### ISSUE THREAD

**Issue by anasanasanas** [Karn/notify#29]
Is there a reason why the minSdkVersion is not 17?
Thanks for the great library

**Comment by Karn** [comment]
Hello @anasanasanas,

There is was no rationale for selecting 19 if I'm being honest. If I recall correctly, I think it was initialized with 19 as the target when I created the project.

You can open a PR with the minSdkVersion reduced to 17 and if the tests pass I can merge it in.

For my reference: https://developer.android.com/guide/topics/ui/notifiers/notifications#compatibility

**Comment by anasanasanas** [comment]
@Karn Done.
