### ISSUE TITLE
See source

### ISSUE THREAD

**Issue by bernaferrari** [Karn/notify#36]
I don't know why or how, but I can't command+click on a Notify instruction to see the code. Everywhere else, things work fine.

![image](https://user-images.githubusercontent.com/351125/55665492-1f0dc900-5817-11e9-81d7-c51569335b17.png)

![image](https://user-images.githubusercontent.com/351125/55665494-2fbe3f00-5817-11e9-9a77-c9217bba6087.png)

If I were you, I would probably double-check if you are not compiling them before sending to maven or something like that.

**Comment by Karn** [comment]
@bernaferrari This is interesting, I'll have to investigate this further. Thanks for pointing it out.

**Comment by Karn** [comment]
@bernaferrari The latest develop branch should now be generating sources as expected. Thanks for pointing this out!
