### ISSUE TITLE
Failed to resolve: io.karn:notify:1.2.1

### ISSUE THREAD

**Issue by kishansinhparmar** [Karn/notify#39]
Gradle sync project failed...

Android Studio 3.3.2
Build #AI-182.5107.16.33.5314842, built on February 16, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

Gradle version: com.android.tools.build:gradle:3.3.2

**Comment by kishansinhparmar** [comment]
Mistakly writes in the wrong brackets.

**Comment by kabirnayeem99** [comment]
Anyone wondering how he solved the issue, you need to add the maven repository under allprojects, not under buildscript. 

`buildscript {
    repositories {
        jcenter()
        // DO NOT ADD IT HERE!!!
    }
    ...
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        // ADD IT HERE
        maven { url "https://jitpack.io" }
    }
}`

For further information, refer to this stackoverflow question [jitpack.io failed to resolve github repo](https://stackoverflow.com/questions/33058358/jitpack-io-failed-to-resolve-github-repo).
