### ISSUE TITLE
Custom id Notifications

### ISSUE THREAD

**Issue by hrupin** [Karn/notify#42]
Hello. 
Thank you very match for you library. This GREAT library!!!

And how can you set your unique notification ID?

**Comment by Karn** [comment]
It's a simple change! I have a PR open which you can use by modifying the gradle dependency as follows: `implementation 'io.karn:notify:feature~configurable-notification-id-SNAPSHOT'`.
You can give the notification a unique it by passing an integer as an argument to the `show(...)` function.

E.g:
```kotlin
Notify.with(this.context)
    .content {
        title = "New dessert menu"
        text = "The Cheesecake Factory has a new dessert for you to try!"
    }.show(NOTIFICATION_ID)
```

**Comment by Karn** [comment]
@hrupin I've merged the PR into develop you can now use the following dependency:
`implementation 'io.karn:notify:develop-SNAPSHOT'`
