### ISSUE TITLE
IMPORTANCE_NORMAL without sound

### ISSUE THREAD

**Issue by NLLAPPS** [Karn/notify#53]
Hi, I am not sure if I am missing something but I cannot seem to find a way to create a channel/notification with priority IMPORTANCE_NORMAL but without sound.
For example

    `Payload.Alerts(
                channelKey = "test",
                lockScreenVisibility = NotificationCompat.VISIBILITY_PUBLIC,
                channelName = "test,
               channelImportance = Notify.IMPORTANCE_LOW

        )`

Does not have any sound but listed towards the bottom. I want a normal notification so I use

    `Payload.Alerts(
                channelKey = "test",
                lockScreenVisibility = NotificationCompat.VISIBILITY_PUBLIC,
               channelName = "test,
               channelImportance = Notify.IMPORTANCE_NORMAL

        )`

But this plays sound.

How can I have IMPORTANCE_NORMAL without sound?

**Comment by Karn** [comment]
Hey there!

You might be able to do this by providing a `sound` for the NORMAL notification which is just an empty audio track. That should allow you to achieve what you would want.

See: https://github.com/Karn/notify/blob/develop/library/src/main/java/io/karn/notify/entities/Payload.kt#L144

**Comment by NLLAPPS** [comment]
Thanks. Wouldn't it be possible to provide a switch/option to preventing library setting the default sound?

**Comment by Karn** [comment]
@NLLAPPS it's possible to do so, however I'm not entirely sure if it's a feature that many users would find beneficial. I can keep it in the backlog and should there be more interest, I'm happy to add the feature.
