### ISSUE TITLE
Support for setShowBadge

### ISSUE THREAD

**Issue by NLLAPPS** [Karn/notify#55]
Hi,  are there any plans for supporting [setShowBadge ](https://developer.android.com/reference/android/app/NotificationChannel#setShowBadge(boolean))in channel config? 

Thanks

**Comment by cyzaoj** [comment]
+ 1

**Comment by Karn** [comment]
Should now be available in the latest develop (0b5d56e3fbfb68770953132b4c829eecbb600579)!
