### ISSUE TITLE
NotificationChannelInterop.with add 3 to alerting.channelImportance

### ISSUE THREAD

**Issue by NLLAPPS** [Karn/notify#61]
Hi, what is the reason for "+3" in this line?
NotificationChannel(alerting.channelKey, alerting.channelName, alerting.channelImportance + 3)

**Comment by Karn** [comment]
Hey @NLLAPPS! This is done because the channel importance is set with accordance to the legacy importance that was used before Notification channels were introduced. The +3 is a quick way to keep the same scheme and be forward-compatible since the value of the channel is exposed as an "enum".
