### ISSUE TITLE
How to create child notifications

### ISSUE THREAD

**Issue by gvravikumar** [Karn/notify#62]
I have a use case where I need to show child notifications. Like gmail, individual mails have their respective minimise icon to the right. Like minimise icon is there to the right of individual email timestamp
![Screenshot_2020-03-17-05-30-24-970_com android chrome](https://user-images.githubusercontent.com/37646894/76809329-72064380-6810-11ea-88b3-38b2b39678fc.jpg)

**Comment by Karn** [comment]
As per the documentation you should now be able to use the `group` property in the `Payload.Meta` object to decide whether particular notifications can be grouped like this, make sure that the value of the group is the same for all the notification you'd like to group and it should show up like this after 2-3 notifications of the same type depending on what other notifications are shown and how much space is available.

This property should be available in the latest develop (0b5d56e3fbfb68770953132b4c829eecbb600579)!
