### ISSUE TITLE
Multiple notifications with different Ids and meta Intents appear to use first meta Intent

### ISSUE THREAD

**Issue by RiballoJose** [Karn/notify#65]
When I show more than one notification with different Ids and different onClick behaviors, I receive the first notification Intent instead of the clicked one.

`clearIntent = PendingIntent.getService(
                        this,
                        0,
                        Intent(this, Service::class.java)
                            .apply {
                                action = MY_ACTION
                                val bundle = Bundle(1)
                                bundle.putInt(ID, id)
                                replaceExtras(bundle)
                            },
                        0
                    )`

**Comment by Karn** [comment]
Hey @RiballoJose, do you mind sharing some sample code. I can take a deeper look and see what's going on!

**Comment by RiballoJose** [comment]
Hi @Karn, thanks for your quick support.  This is the piece of code where I put notifications.
`
val open = PendingIntent.getService(
            this@NotificationService,
            0,
            Intent(this@NotificationService, NotificationService::class.java).apply {
                action = ACTION_OPEN
                putExtra(ID, id)
            },
            0
        )
Notify
        .with(this)
        .meta {
            clickIntent = open
        }
        .asMessage {
            userDisplayName =
                SpannableStringBuilder().bold { row.user.getFullName() + ":" }
            messages = pendingList.map { msg ->
                NotificationCompat.MessagingStyle.Message(
                    msg.text, msg.date * 1000, person
                )
            }
        }
        .show(row.user.id)
`

When I receive the intent of the notification, it always receive the first intent extra ID:
`
override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    when (intent?.action) {
            ACTION_OPEN -> {
                val id = intent.getIntExtra(ID, -1) 
               // This is always the id of the first Notification I showed, even when it was cancelled
            }
...
`

Its like the _meta_ part is instantiate only the first time I put a notification. I tried different ways, this code shows one of them. All seems to work in the same way.

Thanks in advance, if you need something else, please, let me know.

**Comment by Karn** [comment]
Hey @RiballoJose, I just double-checked and the notification's clickIntent should be recreated anytime you use show.

The way I understand it, you're trying to do the following:

```kotlin
val id = 1
val open = PendingIntent.getService(this@NotificationService, 0, Intent(this@NotificationService, NotificationService::class.java).apply {
  action = ACTION_OPEN
  putExtra(ID, id)
}, 0)

val shownNotificationId = Notify.with(this)
  .meta { clickIntent = open }
  .asMessage {
    userDisplayName = SpannableStringBuilder().bold { row.user.getFullName() + ":" }
    messages = pendingList.map { msg -> NotificationCompat.MessagingStyle.Message(msg.text, msg.date * 1000, person) }
  }
  .show()
```

If you want to show another notification, you can then create a new notification but update the intent. Continuing from the above example, you'd then do the following:

```kotlin
// Optionally cancel the previous notification
Notify.cancelNotification(shownNotificationId)

val id2 = 2 // Create new ID
val open2 = PendingIntent.getService(this@NotificationService, 0, Intent(this@NotificationService, NotificationService::class.java).apply {
  action = ACTION_OPEN
  putExtra(ID, id2)
}, 0) // Create new pending intent based on new ID

val shownNotificationId2 = Notify.with(this)
  .meta { clickIntent = open2 } // This is now 'open2' instead of 'open'
  .asMessage {
    userDisplayName = SpannableStringBuilder().bold { row.user.getFullName() + ":" }
    messages = pendingList.map { msg -> NotificationCompat.MessagingStyle.Message(msg.text, msg.date * 1000, person) }
  }
  .show()
```

That should then trigger the `open2` PendingIntent when the second notification is clicked.
