### ISSUE TITLE
Unresolved reference: progress

### ISSUE THREAD

**Issue by ZiraiMode** [Karn/notify#66]
I cannot create progress notification because it cannot find function `.progress`

Version of library: 1.3.0

![image](https://user-images.githubusercontent.com/27578886/85905918-197e1380-b80d-11ea-896a-0320d07569ab.png)

**Comment by Karn** [comment]
Hey @P1NG2WIN!

The progress functionality has not been released yet, you can use the latest snapshot to get the feature.

```
// Module level build.gradle
dependencies {
    implementation "io.karn:notify:develop-SNAPSHOT"
}
```

A gradle sync should bring the latest changes in and you should see the progress functionality.

Cheers!

**Comment by aandis** [comment]
any eta for releasing it?

**Comment by ZiraiMode** [comment]
+1 

> any eta for releasing it?
