### ISSUE TITLE
Problem getting dependency via Gradle 

### ISSUE THREAD

**Issue by omensight** [Karn/notify#69]
I am getting this problem when I try to get the dependency from jitpack
![image](https://user-images.githubusercontent.com/34387536/89091963-ba676d80-d37b-11ea-9c88-59bc45515770.png)

I am using this
```
repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
```

Don't know why I can't add the dependency, thanks in advance.

**Comment by Karn** [comment]
Sometimes it takes a sync or two to get the package from jitpack. I've found it to be flakey at times. I've verified on a new project to ensure that the package can be downloaded successfully.
Let me know if you're still having issues by reopening this issue.
