### ISSUE TITLE
The released 1.3.0 does not include progress notification codes

### ISSUE THREAD

**Issue by yhz61010** [Karn/notify#70]
1. The source code in library contains the progress notification codes. However, the released 1.3.0 version doesn't have it.
2. Although I can update the progress by calling `notificationManager.notify()`, I hope if there is any handy method to update it will be wonderful.

**Comment by DALIHILLARY** [comment]
Same problem there

**Comment by ZiraiMode** [comment]
+1 about  `notificationManager.notify()`

**Comment by Karn** [comment]
Hey @yhz61010, I've just now released a new version of the library (1.4.0) which should have the progress notification functionality.

Cheers!
Karn
