### ISSUE TITLE
Notification display problem

### ISSUE THREAD

**Issue by Android-wangmeng** [Karn/notify#71]
The notification doesn't pop up, it just shows up in the notification bar

**Comment by Karn** [comment]
Hi @Android-wangmeng, this might be related to your notification settings. I've seen some devices where when the notification priority is set to normal, the notification does not pop up. Also, be sure to check that you don't have Do Not Disturb mode enabled.

**Comment by Android-wangmeng** [comment]
How to set the priority of this framework?

**Comment by ZiraiMode** [comment]
> How to set the priority of this framework?

.alerting { 
     channelImportance = Notify.IMPORTANCE_HIGH
}

It's strange that wiki doesn't have information about alerting block
