### ISSUE TITLE
How to set the priority of the notify ?

### ISSUE THREAD

**Issue by jackyHuangH** [Karn/notify#76]
I want to set the priority of notifies,but i coudn't found how to make it

**Comment by Karn** [comment]
Hey @jackyHuangH,

You can use the [`Alert`](https://github.com/Karn/notify/blob/develop/library/src/main/java/io/karn/notify/entities/Payload.kt#L133-L136) section to configure this.

Cheers!

**Comment by jackyHuangH** [comment]
> Hey @jackyHuangH,
> 
> You can use the [`Alert`](https://github.com/Karn/notify/blob/develop/library/src/main/java/io/karn/notify/entities/Payload.kt#L133-L136) section to configure this.
> 
> Cheers!
Got it!Thx
